# Generated by Django 4.2.13 on 2024-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_query', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YTSong',
        ),
        migrations.DeleteModel(
            name='YTVideo',
        ),
    ]
