# Generated by Django 4.2.13 on 2024-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiry',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='test_char_field',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
