# Generated by Django 4.2.13 on 2024-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_expiry_profile_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state0',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state1',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
