# Generated by Django 4.2.13 on 2024-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0001_initial'),
        ('profiles', '0004_profile_code_profile_state0_profile_state1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state0',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test_char_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.AddField(
            model_name='profile',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yt_auth.credentials'),
        ),
    ]
