# Generated by Django 4.2.13 on 2024-06-08 16:29

from django.db import migrations, models
import django.db.models.deletion
import yt_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0002_remove_credentials_authorization_path_and_more'),
        ('profiles', '0005_remove_profile_code_remove_profile_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credentials',
            field=models.OneToOneField(default=yt_auth.models.Credentials, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='yt_auth.credentials'),
        ),
    ]
