# Generated by Django 4.2.13 on 2024-06-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
