# Generated by Django 4.2.13 on 2024-06-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_youtube_id_profile_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_guest', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
