# Generated by Django 4.2.13 on 2024-06-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0006_remove_credentials_date_acquired'),
        ('profiles', '0008_guestprofile_profile_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credentials',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='yt_auth.credentials'),
        ),
    ]
