# Generated by Django 4.2.13 on 2024-06-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0006_remove_credentials_date_acquired'),
        ('profiles', '0011_alter_profile_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credentials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yt_auth.credentials'),
        ),
    ]
