# Generated by Django 4.2.13 on 2024-06-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0006_remove_credentials_date_acquired'),
        ('profiles', '0013_alter_profile_is_active_alter_profile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credentials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='yt_auth.credentials'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
