# Generated by Django 4.2.13 on 2024-06-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestProfile',
        ),
    ]
