# Generated by Django 4.2.13 on 2024-06-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_profile_email_alter_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='youtube_url',
            new_name='youtube_handle',
        ),
    ]
