# Generated by Django 4.2.13 on 2024-06-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_response', models.JSONField(null=True)),
                ('error_msg', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_nickname', models.CharField(max_length=100, null=True)),
                ('user_email', models.CharField(max_length=100, null=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('queue_title', models.CharField(max_length=100, null=True)),
                ('queue_id', models.CharField(max_length=100, null=True)),
                ('entry_title', models.CharField(max_length=100, null=True)),
                ('entry_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
