# Generated by Django 4.2.13 on 2024-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('error_msg', models.CharField(max_length=500)),
                ('session', models.JSONField()),
                ('user_dict', models.JSONField()),
            ],
        ),
    ]
