# Generated by Django 4.2.13 on 2025-01-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestReport',
        ),
    ]
