# Generated by Django 4.2.13 on 2024-06-10 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='collaborators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.CharField(default='none given', max_length=100),
        ),
        migrations.AddField(
            model_name='queue',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
