# Generated by Django 4.2.13 on 2024-06-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_queue_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.queue'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
