# Generated by Django 4.2.13 on 2024-06-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_queue_owner_yt_id_queue_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='queues.queue'),
        ),
    ]
