# Generated by Django 4.2.13 on 2024-06-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_entry_published_queue_published_queue_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='published',
        ),
    ]
