# Generated by Django 4.2.13 on 2024-06-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_remove_queue_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['number']},
        ),
    ]
