# Generated by Django 4.2.13 on 2024-06-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0014_alter_queue_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
