# Generated by Django 4.2.13 on 2024-06-12 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0015_alter_queue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='collaborators',
            field=models.ManyToManyField(related_name='other_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
