# Generated by Django 4.2.13 on 2024-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0017_alter_entry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
