# Generated by Django 4.2.13 on 2024-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0018_alter_entry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.CharField(default='I am embarassed to have added this.', max_length=50),
        ),
    ]
