# Generated by Django 4.2.13 on 2024-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0019_alter_entry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='number',
            new_name='position',
        ),
        migrations.AddField(
            model_name='entry',
            name='old_position',
            field=models.IntegerField(default=-1),
        ),
    ]
