# Generated by Django 4.2.13 on 2024-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0020_alter_entry_options_rename_number_entry_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
