# Generated by Django 4.2.13 on 2024-06-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0021_entry_synced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='queue',
            new_name='p_queue',
        ),
    ]
