# Generated by Django 4.2.13 on 2024-06-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0023_entry_kind_entry_resource_id_queue_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='resource_id',
            new_name='yt_id',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='resource_id',
            new_name='yt_id',
        ),
    ]
