# Generated by Django 4.2.13 on 2024-06-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0024_rename_resource_id_entry_yt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='synced',
        ),
    ]
