# Generated by Django 4.2.13 on 2024-06-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0025_remove_queue_synced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='yt_id',
            new_name='playlist_item_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='old_position',
        ),
    ]
