# Generated by Django 4.2.13 on 2024-06-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0026_rename_yt_id_entry_playlist_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='playlist_item_id',
            new_name='yt_id',
        ),
    ]
