# Generated by Django 4.2.13 on 2024-06-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0027_rename_playlist_item_id_entry_yt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
