# Generated by Django 4.2.13 on 2024-06-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0028_queue_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='name',
        ),
    ]
