# Generated by Django 4.2.13 on 2024-06-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0029_remove_queue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['_position']},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='position',
            new_name='_position',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='length',
        ),
    ]
