# Generated by Django 4.2.13 on 2024-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0031_remove_queue_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
