# Generated by Django 4.2.13 on 2024-06-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0033_remove_queue_owner_yt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='duration',
        ),
    ]
