# Generated by Django 4.2.13 on 2025-08-19 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0034_remove_entry_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
