# Generated by Django 4.2.13 on 2024-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('expiry', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('authorization_path', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('state0', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('state1', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
