# Generated by Django 4.2.13 on 2024-06-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='authorization_path',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='code',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='state0',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='state1',
        ),
    ]
