# Generated by Django 4.2.13 on 2024-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0002_remove_credentials_authorization_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='has_tokens',
            field=models.BooleanField(default=False),
        ),
    ]
