# Generated by Django 4.2.13 on 2024-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_auth', '0003_credentials_has_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='account',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='scopes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='token_uri',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='universe_domain',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
